# Data file paths
data:
  data_path: "data"
  raw_path: "raw"
  processed_path: "processed"
  saved_objects_path: "saved_objects"
  reports_path: "reports"
  figures_path: "figures"
  maps_path: "maps"

# Default XGBoost model parameters
xgboost_default:
  n_estimators: 500
  learning_rate: 0.05
  max_depth: 5
  subsample: 0.8
  colsample_bytree: 0.8

# Default XGBoost setup parameters
xgboost_setup:
  random_state: 37
  eval_metric: "mae"
  tree_method: "hist"
  device: "cuda" 

# Modelling constants
modelling:
  daily_steps: [1, 2, 3, 7, 14, 30, 60, 180, 365, 500, 546]
  daily_fourier_features: ["YE", "W"] # Yearly, weekly
  daily_linear_trends: [1, 2, 3, 4, 5] # trends for the first linear forecast
  daily_hybrid_trends: [1, 2]
  hourly_steps: [1, 2, 4, 6, 12, 24, 48, 72, 96, 120, 168, 336, 720]
  hourly_fourier_features: ["WE", "D"] # Weekly, daily
  hourly_linear_trends: [1, 2, 3, 4, 5] # trends for the first linear forecast
  hourly_hybrid_trends: [1, 2] 
  hourly_num_lags: 168 # number of lags to use for the hourly models (there are around 4710)

# Hyperparameter tuning settings
hyperparameter_tuning:
  n_splits: 5
  daily_test_size: 30
  hourly_test_size: 168
  max_evals: 100

# Model naming conventions
model_naming:
  linear_model_prefix: "linear_order"
  default_non_linear: "base_non_linear"
  hybrid_model_prefix: "hybrid_order"

# Model signatures 
model_sigs:
  daily_linear: "5_order_linear_daily" # if you change the number of daily linear trends you may want to change the 5 here
  hourly_linear: "5_order_linear_hourly"
  daily_hybrid: "2_order_hybrid_daily"
  hourly_hybrid: "2_order_hybrid_hourly"

# Saving conventions
saving:
  model_file_suffix: "model.pkl"
  hybrid_file_suffix: "hybrid.pkl"
  dp_file_suffix: "dp.pkl"
  design_file_suffix: "design.pkl"
  target_file_suffix: "target.pkl"
  linear_keys_preffix: "linear_keys"
  non_linear_keys_preffix: "non_linear_keys"
  daily_lags: "daily"
  hourly_lags: "hourly"
  lags_sig: "eda"
  lags_preffix: "sig_lags"
  hyperparams_preffix: "hyperparams"
  ts_prefix: "ts"
  ts_daily: "daily"
  ts_hourly: "hour"
  original_parquet_prefix: "processed"
  jfk_parquet_prefix: "processed_jfk"


